{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n  +4\n  -5", "trace": ">   ???\nE   assert 4 == 5\nE     +4\nE     -5\n\n/Users/juanxu/Documents/霍格沃兹培训/测试demo/PytestLuboProject/测试ini文件/test_first.py:12: AssertionError"}, "start": 1634456273573, "stop": 1634456273574, "uuid": "188937ca-658a-482e-9f01-dcc45ce23c30", "historyId": "a47aba09a6ceb6948e83217d296644db", "testCaseId": "d44fdcc26139878a41adb72c4b63b43b", "fullName": "testini.test_first#test_answer", "labels": [{"name": "parentSuite", "value": "testini"}, {"name": "suite", "value": "test_first"}, {"name": "host", "value": "xixi"}, {"name": "thread", "value": "16424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testini.test_first"}]}